import { describe, it, expect } from 'vitest'
import {
    formatCPF,
    unformatCPF,
    isValidCPF,
    formatWhatsApp,
    unformatWhatsApp,
    formatCurrency,
    parseCurrency,
} from '@/lib/formatters'

// ─────────────────────────────────────────────────────────────────────────────
// formatCPF
// ─────────────────────────────────────────────────────────────────────────────

describe('formatCPF', () => {
    it('should apply mask to a raw 11-digit CPF', () => {
        expect(formatCPF('12345678901')).toBe('123.456.789-01')
    })

    it('should apply partial mask while user is typing (6 digits)', () => {
        expect(formatCPF('123456')).toBe('123.456')
    })

    it('should strip non-numeric characters before masking', () => {
        expect(formatCPF('123.456.789-01')).toBe('123.456.789-01')
    })

    it('should truncate to 11 digits when input is longer', () => {
        expect(formatCPF('123456789012345')).toBe('123.456.789-01')
    })

    it('should return empty string for empty input', () => {
        expect(formatCPF('')).toBe('')
    })
})

// ─────────────────────────────────────────────────────────────────────────────
// unformatCPF
// ─────────────────────────────────────────────────────────────────────────────

describe('unformatCPF', () => {
    it('should remove all non-numeric characters', () => {
        expect(unformatCPF('123.456.789-01')).toBe('12345678901')
    })

    it('should return same string if already digits only', () => {
        expect(unformatCPF('12345678901')).toBe('12345678901')
    })

    it('should return empty string for empty input', () => {
        expect(unformatCPF('')).toBe('')
    })
})

// ─────────────────────────────────────────────────────────────────────────────
// isValidCPF
// ─────────────────────────────────────────────────────────────────────────────

describe('isValidCPF', () => {
    it('should return true for a valid CPF', () => {
        // Known valid CPF generated by algorithm
        expect(isValidCPF('529.982.247-25')).toBe(true)
    })

    it('should return false for a CPF with repeated digits', () => {
        expect(isValidCPF('111.111.111-11')).toBe(false)
    })

    it('should return false for CPF with wrong length', () => {
        expect(isValidCPF('123.456')).toBe(false)
    })

    it('should return false for all-zeros CPF', () => {
        expect(isValidCPF('000.000.000-00')).toBe(false)
    })

    it('should return false for invalid check digits', () => {
        expect(isValidCPF('123.456.789-00')).toBe(false)
    })

    it('should accept unformatted string', () => {
        expect(isValidCPF('52998224725')).toBe(true)
    })
})

// ─────────────────────────────────────────────────────────────────────────────
// formatWhatsApp
// ─────────────────────────────────────────────────────────────────────────────

describe('formatWhatsApp', () => {
    it('should apply cellphone mask (11 digits)', () => {
        expect(formatWhatsApp('11999998888')).toBe('(11) 99999-8888')
    })

    it('should apply landline mask (10 digits)', () => {
        expect(formatWhatsApp('1133334444')).toBe('(11) 3333-4444')
    })

    it('should strip non-numeric characters before masking', () => {
        expect(formatWhatsApp('(11) 99999-8888')).toBe('(11) 99999-8888')
    })

    it('should truncate to 11 digits when input is longer', () => {
        expect(formatWhatsApp('119999988889999')).toBe('(11) 99999-8888')
    })

    it('should return empty string for empty input', () => {
        expect(formatWhatsApp('')).toBe('')
    })
})

// ─────────────────────────────────────────────────────────────────────────────
// unformatWhatsApp
// ─────────────────────────────────────────────────────────────────────────────

describe('unformatWhatsApp', () => {
    it('should strip parentheses, spaces, and dashes', () => {
        expect(unformatWhatsApp('(11) 99999-8888')).toBe('11999998888')
    })
})

// ─────────────────────────────────────────────────────────────────────────────
// formatCurrency
// ─────────────────────────────────────────────────────────────────────────────

describe('formatCurrency', () => {
    it('should format zero correctly', () => {
        expect(formatCurrency(0)).toBe('R$\u00a00,00')
    })

    it('should format positive amount with BRL symbol and comma separator', () => {
        const result = formatCurrency(1234.56)
        expect(result).toContain('1.234,56')
        expect(result).toContain('R$')
    })

    it('should format large amount with thousand separators', () => {
        const result = formatCurrency(1000000)
        expect(result).toContain('1.000.000,00')
    })

    it('should format negative amount', () => {
        const result = formatCurrency(-50)
        expect(result).toContain('50')
    })
})

// ─────────────────────────────────────────────────────────────────────────────
// parseCurrency
// ─────────────────────────────────────────────────────────────────────────────

describe('parseCurrency', () => {
    it('should parse BRL formatted string to number', () => {
        expect(parseCurrency('R$ 1.234,56')).toBe(1234.56)
    })

    it('should parse simple comma-decimal string', () => {
        expect(parseCurrency('10,50')).toBe(10.5)
    })

    it('should return 0 for empty string', () => {
        expect(parseCurrency('')).toBe(0)
    })

    it('should return 0 for non-numeric string', () => {
        expect(parseCurrency('abc')).toBe(0)
    })

    it('should handle string without decimal', () => {
        expect(parseCurrency('100')).toBe(100)
    })
})
